iteration: 1.0
tickets_processed: True
forecast_scenario: core
export_folder: E:\NorMITs Demand
assignment_model: NoRMS

# Input paths
matrices_to_grow_dir: I:\Transfer\edge_replicant_xfer\Outputs

# Custom inputs files
demand_segments: I:\NorMITs Demand\import\edge_replicant\apply_growth\demand_segments.csv
ticket_type_splits: 
                    flow_cat_path: I:\NorMITs Demand\import\edge_replicant\apply_growth\FlowCats.csv
                    
cube_exe: C:\Program Files\Citilabs\CubeVoyager\VOYAGER.EXE

# EDGE outputs
edge_growth_dir: I:\NorMITs Demand\import\EDGE_growth\Edge distance\Nov 21 Central - Growth

# Forecast years dictionary
# forecast year: EDGE growth factors file
forecast_years:
  2040: Out_Nov 21 Central - Growth_2040_rate.csv.bz2