iteration: 1.review
forecast_scenario: Regional
export_folder: C:\Work\NoRMS\NorMITs_Demand\Exports
assignment_model: NoRMS

# Input paths
matrices_to_grow_dir: C:\Work\NoRMS\NorMITs_Demand\Exports

# Custom inputs files
demand_segments: U:\00_Inputs\GATInputs\demand_segments.csv
flow_cat_path: U:\00_Inputs\GATInputs\FlowCats.csv
ticket_type_splits_path: U:\00_Inputs\GATInputs\TicketTypeSplits_DS.csv
norms_to_edge_stns_path: C:\Work\NoRMS\NorMITs_Demand\Exports\TLCs.csv
cube_exe: C:\Program Files\Citilabs\CubeVoyager\VOYAGER.EXE

# EDGE Inputs
edge_flows_path: U:\00_Inputs\GATInputs\FC_fullfat1819_NEW_DDG.csv

# EDGE outputs
edge_growth_dir: I:\NorMITs Demand\import\edge_replicant\edge_inputs\output_data\Outputs\Jan 24 Central - Growth

# Forecast years dictionary
# forecast year: EDGE growth factors file
forecast_years:
  2036: Out_Jan 24 Central - Growth_2036_rate.csv.bz2
  2043: Out_Jan 24 Central - Growth_2043_rate.csv.bz2
  2045: Out_Jan 24 Central - Growth_2045_rate.csv.bz2