iteration: 1.review
forecast_scenario: Regional
export_folder: C:\Work\NoRMS\temp\normits
assignment_model: NoRMS

# Input paths
matrices_to_grow_dir: C:\Work\NoRMS\temp\normits
irsj_props_dir: C:\Work\NoRMS\temp\normits

# Custom inputs files
demand_segments: U:\00_Inputs\GATInputs\demand_segments.csv
norms_to_edge_stns_path: C:\Work\NoRMS\temp\normits\TLCs.csv
ticket_type_splits:
  edge_flows_path: U:\00_Inputs\GATInputs\FC_fullfat1819_NEW_DDG.csv
  splits_path: C:\Work\NoRMS\temp\normits\split_dir
  flow_cat_path: U:\00_Inputs\GATInputs\FlowCats.csv
  info: info

cube_exe: C:\Program Files\Citilabs\CubeVoyager\VOYAGER.EXE

# EDGE outputs
edge_growth_dir: I:\NorMITs Demand\import\edge_replicant\edge_inputs\output_data\Outputs\Apr 23 Reg

# Forecast years dictionary
# forecast year: EDGE growth factors file
forecast_years:
  2028: Out_Apr 23 Reg_2028_rate.csv.bz2
  2043: Out_Apr 23 Reg_2043_rate.csv.bz2
