[tool.black]
line-length = 95

# Pylint settings
[tool.pylint.basic]
good-names="df, x"

[tool.pylint.messages_control]
disable = [
    "C0330",            # Compatibility with black
    "C0326",            # Compatibility with black
    "line-too-long",    # Compatibility with black
    "line-many-line",
    "use-dict-literal",
    "use-list-literal",
]

[tool.pylint.design]
max-arguments = 10
max-attributes = 15
max-statements = 100

[tool.mypy]
ignore_missing_imports = true
