[tool.black]
line-length = 95

[tool.pylint.messages_control]
disable = [
    "C0330",            # Compatibility with black
    "C0326",            # Compatibility with black
    "line-too-long",    # Compatibility with black
    "line-many-line",
]
