[tool.black]
line-length = 95

[tool.pylint.messages_control]
disable = [
    "C0330",            # Compatibility with black
    "C0326",            # Compatibility with black
    "line-too-long",    # Compatibility with black
    "line-many-line",
    "use-dict-literal",
    "use-list-literal",
]

# Pylint settings
[tool.pylint.basic]
good-names = ["df", "tp", "x", "i", "f"]

[tool.pylint.design]
max-attributes = 15
max-args = 10

[tool.mypy]
ignore_missing_imports = true
