iteration: 1.0
forecast_scenario: core
export_folder: I:\NorMITs Demand
assignment_model: NoRMS
assignment_model_run_folder: I:\NorMITs Demand\norms
assignment_run_id: 1
base_matrix_folder: I:\NorMITs Demand\norms
forecast_year: 2040
pEDGE_folder: I:\NorMITs Demand\norms\pEDGE
edge_flows_filename: FC_fullfat1819_NEW_DDG.csv
edge_factors_filename: Out_Nov 21 Central - Growth_{forecast_year}_rate.csv
lookups_folder: I:\NorMITs Demand\norms\pEDGE
