iteration: 2.0
base_output_folder: I:\NorMITs Demand\Traveller Segmentation Tool
notem_iteration: 9.10
notem_export_home: I:\NorMITs Demand\NoTEM
scenario: SC01_JAM
model: NoRMS
year: 2018
disaggregation_output_segment: soc
trip_length_distribution_folder: I:\NorMITs Demand\import\traveller_segment_tool\trip_length_distributions\v1.1\uc_m_soc_m6
cost_folder: I:\NorMITs Demand\import\modal\train\costs\norms\userclass
matrix_parameters:
  folder: I:\NorMITs Demand\Distribution Model\iter9.10.3\train\Final Outputs\Full TP PA Matrices
  zoning_system_name: norms
  segmentation_name: hb_p_m
  aggregate_segmentation_name: hb_p_m
disaggregation_settings:
  export_original: yes
  export_furness: no
  maximum_furness_loops: 1999
  pa_furness_convergence: 0.1
  bandshare_convergence: 0.975
  max_bandshare_loops: 200
  multiprocessing_threads: -1
  pa_match_tolerance: 0.95
  minimum_bandshare_change: 1e-04
  trip_end_constraint: none
