output_folder: I:\NorMITs Demand\import\edge_replicant\edge_inputs\Drivers\Nov 21 NPIER - North factored\Central Comparison
npier_ddg_folder: I:\NorMITs Demand\import\edge_replicant\edge_inputs\Drivers\Nov 21 NPIER - North factored
npier_scenario: NPIER
eddie_ddg_folder: I:\NorMITs Demand\import\edge_replicant\edge_inputs\Drivers\Nov 21 central
eddie_scenario: Central
date: Nov21
heatmap_years:
  - 2018
  - 2038
comparison_ddgs:
  - Emp
  - Pop
base_year: 2018
